/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Software;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author rocky
 */
public class DeleteForm extends javax.swing.JFrame {

    /**
     * Creates new form DeleteForm
     */
    public DeleteForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldForDeleteRecord = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelForInvalidId = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Window");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 102));
        jLabel1.setText("Delete Record");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setText("@RitikCoder.com");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jTextFieldForDeleteRecord.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldForDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForDeleteRecordActionPerformed(evt);
            }
        });
        jTextFieldForDeleteRecord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldForDeleteRecordKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldForDeleteRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 330, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Student ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 120, 40));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 110, 40));

        jLabelForInvalidId.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabelForInvalidId.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(jLabelForInvalidId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 310, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Software/BGForDelete2.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldForDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForDeleteRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldForDeleteRecordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
//        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String stringForStudentID = jTextFieldForDeleteRecord.getText();
        boolean booleanForCheckStudentIDRecord = false;
        boolean booleanForCheckAdminPassword = false;
        //System.out.println(stringForStudentID);
        //System.out.println(stringForComformPasswrodToDeleteRecord);

        if (jTextFieldForDeleteRecord.getText().trim().isEmpty()) {
            jLabelForInvalidId.setText("Student ID is Empty");
        } else {
            //mysql Connecction is here.
            try {
                String stringForComformPasswrodToDeleteRecord = JOptionPane.showInputDialog("Enter your password here.");
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/learningcomputer", "root", "RitikCoder@mysql");
                Statement statement = connection.createStatement();
                //System.out.println("Connection establized successfully.");
                String stringForExecuteQuery = "Select Password from loginadmin";
                ResultSet resultSet = statement.executeQuery(stringForExecuteQuery);
                while (resultSet.next()) {
                    if (stringForComformPasswrodToDeleteRecord.equals(resultSet.getString(1))) {
                        booleanForCheckAdminPassword = false;
                        //System.out.println("password is mateched successfully to the database.");
                        String stringForExecuteQuery1 = "Select Student_ID from studentdata";
                        resultSet = statement.executeQuery(stringForExecuteQuery1);
                        while (resultSet.next()) {
                            if (stringForStudentID.equalsIgnoreCase(resultSet.getString(1))) {
                                booleanForCheckStudentIDRecord = false;
//                            System.out.println("Student_ID is matched to the database.");
//                            String stringForStudentIDToDeleteRecord= stringForStudentID;
                                int conformDilogBox = JOptionPane.showConfirmDialog(null, "Do you want to delete", "Delete", JOptionPane.YES_NO_OPTION);
                                if (conformDilogBox == 0) {
                                    String stringForExecuteQuery2 = "delete from studentdata where Student_ID= ?";
                                    //System.out.println("query run successfully.");
                                    //resultSet= statement.executeQuery(stringForExecuteQuery2);
                                    PreparedStatement preparedStatement = connection.prepareStatement(stringForExecuteQuery2);
                                    preparedStatement.setString(1, stringForStudentID);
                                    preparedStatement.executeUpdate();
                                    //System.out.println("query update successfully.");
                                    JOptionPane.showMessageDialog(rootPane, "Record is Deleted successfully on ID= " + stringForStudentID + "");
                                    jTextFieldForDeleteRecord.setText("");
                                }
                                break;
                            } else {
                                booleanForCheckStudentIDRecord = true;
                                //break;
                            }
                        }
                        break;
                    } else {
                        booleanForCheckAdminPassword = true;
                        //break;
                    }
                }
                if (booleanForCheckStudentIDRecord) {
                    JOptionPane.showMessageDialog(null, "This Record is not found");
                } else if (booleanForCheckAdminPassword) {
                    JOptionPane.showMessageDialog(null, "Invalid password");
                }
                connection.close();

            } catch (ClassNotFoundException | SQLException ex) {
                System.out.println("Error Found inside of delete record.");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldForDeleteRecordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldForDeleteRecordKeyReleased
        // TODO add your handling code here:
        jLabelForInvalidId.setText("");
    }//GEN-LAST:event_jTextFieldForDeleteRecordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelForInvalidId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldForDeleteRecord;
    // End of variables declaration//GEN-END:variables
}
