/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Software;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author RitikCoder
 */
public class LoginFormForCotching extends javax.swing.JFrame {

    /**
     * Creates new form LoginFormForCotching
     */
    public LoginFormForCotching() {
        initComponents();
        this.jToggleButtonForShowAndHidePassword.setVisible(false);
        this.jLabelForCountDown.setVisible(false);
        //scaleImageSize();
        //jPasswordFieldForLoginPassword.setEchoChar('*');//It is used to change jpassword field pattern.
    }
    
    //Global variable creation.
    int intForLoginTimeLimit;
    Timer timer;
    int second, minute;
    String ddSecond, ddMinutes;
    DecimalFormat decimalFormat= new DecimalFormat("00");
    
    
    //This Method is used to Scale image sizes.
    //void scaleImageSize(){
        //ImageIcon imageIcon= new ImageIcon("C:\\Users\\codew\\OneDrive\\Documents\\NetBeansProjects\\MySoftware1ForCotching\\src\\GUI_Software\\1OpeneyeIcon.png");
        //Image image= imageIcon.getImage();
        //Image image1= image.getScaledInstance(jLabelForShowPassword.getWidth(), jLabelForShowPassword.getHeight(), Image.SCALE_SMOOTH);
        //ImageIcon imageIcon1= new ImageIcon(image1);
        //jLabelForShowPassword.setIcon(imageIcon1);
    //}
    
    //Method of Time to Passwrod Error.
    public void countDownTimer(){
        timer= new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent event){
                second--;
                ddSecond= decimalFormat.format(second);
                ddMinutes= decimalFormat.format(minute);
                jLabelForCountDown.setText("Try again after : "+ ddSecond);
                if(second== -1){
                    second= 59;
                    minute--;
                    jLabelForCountDown.setText("Try again after : "+ ddSecond);
                }
                if(second== 0){
                    timer.stop();
                    jTextFieldForLoginUserID.setEditable(true);
                    jPasswordFieldForLoginPassword.setEditable(true);
                    jLabelForCountDown.setVisible(false);
                    jButtonForLoginLogin.setEnabled(true);
                    
                }
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButtonForShowAndHidePassword = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldForLoginUserID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldForLoginPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonForLoginLogin = new javax.swing.JButton();
        jButtonForLoginCancel = new javax.swing.JButton();
        jLabelForErrorOfUserName = new javax.swing.JLabel();
        jLabelForErrorOfUserPassword = new javax.swing.JLabel();
        jCheckBoxForShowAndHidePassword = new javax.swing.JCheckBox();
        jLabelForCountDown = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login Window");
        setResizable(false);

        jPanel1.setName("Login"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButtonForShowAndHidePassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonForShowAndHidePassword.setText("Show");
        jToggleButtonForShowAndHidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonForShowAndHidePasswordMouseClicked(evt);
            }
        });
        jPanel1.add(jToggleButtonForShowAndHidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 70, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Software/UserID-1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, 60));

        jTextFieldForLoginUserID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldForLoginUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForLoginUserIDActionPerformed(evt);
            }
        });
        jTextFieldForLoginUserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldForLoginUserIDKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldForLoginUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 326, 37));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Software/UserKey-2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, 70));

        jPasswordFieldForLoginPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPasswordFieldForLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldForLoginPasswordActionPerformed(evt);
            }
        });
        jPasswordFieldForLoginPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldForLoginPasswordKeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordFieldForLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 330, 41));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Software/LoginTitle-3.png"))); // NOI18N
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 70));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setText("@RitikCoder.com");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        jButtonForLoginLogin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonForLoginLogin.setText("Login");
        jButtonForLoginLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForLoginLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonForLoginLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 121, 37));

        jButtonForLoginCancel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonForLoginCancel.setText("Cancel");
        jButtonForLoginCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForLoginCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonForLoginCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 121, 37));

        jLabelForErrorOfUserName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabelForErrorOfUserName.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jLabelForErrorOfUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 320, 23));

        jLabelForErrorOfUserPassword.setBackground(new java.awt.Color(102, 97, 103));
        jLabelForErrorOfUserPassword.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabelForErrorOfUserPassword.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jLabelForErrorOfUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 320, 26));

        jCheckBoxForShowAndHidePassword.setBackground(new java.awt.Color(0, 102, 102));
        jCheckBoxForShowAndHidePassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxForShowAndHidePassword.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBoxForShowAndHidePassword.setText("Show Password");
        jCheckBoxForShowAndHidePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxForShowAndHidePasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxForShowAndHidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabelForCountDown.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelForCountDown.setForeground(new java.awt.Color(0, 0, 0));
        jLabelForCountDown.setText("Try again after : ");
        jPanel1.add(jLabelForCountDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 160, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Software/BG-10.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldForLoginUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForLoginUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldForLoginUserIDActionPerformed

    private void jPasswordFieldForLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldForLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldForLoginPasswordActionPerformed

    private void jButtonForLoginLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForLoginLoginActionPerformed
        // TODO add your handling code here:
        //This is my Login button of this Window.
        if(jTextFieldForLoginUserID.getText().trim().isEmpty() && jPasswordFieldForLoginPassword.getText().trim().isEmpty()){
            jLabelForErrorOfUserName.setText("UserID is Empty");
            jLabelForErrorOfUserPassword.setText("Password is Empty");
        }else if(jTextFieldForLoginUserID.getText().trim().isEmpty()){
            jLabelForErrorOfUserName.setText("UserID is Empty");
        }else if(jPasswordFieldForLoginPassword.getText().trim().isEmpty()){
            jLabelForErrorOfUserPassword.setText("Password is Empty");
        }
        else{
        String stringForLoginUserID= jTextFieldForLoginUserID.getText();
        String stringForLoginPassword= new String(jPasswordFieldForLoginPassword.getPassword());
        String stringForUserIDFromDB, stringForPasswordFormDB;
        boolean booleanForCheckIdAndPassword= false;
        try {
            Class<?> forName = Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("Driver Loaded Successfully.");
            Connection connection= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/learningcomputer", "root", "RitikCoder@mysql");
            Statement statement= connection.createStatement();
            //System.out.println("Connection Estabilish Successfully.");
            String stringForQuery= "select *from loginadmin";
            ResultSet resultSet= statement.executeQuery(stringForQuery);
            while(resultSet.next()){
                if(stringForLoginUserID.equalsIgnoreCase(resultSet.getString(1)) && stringForLoginPassword.equals(resultSet.getString(3))){
                    JOptionPane.showMessageDialog(null, "Login Successfully! - "+ stringForLoginUserID);
                    intForLoginTimeLimit= 0;
                    SelectOperationForm selectOperationForm= new SelectOperationForm();
                    selectOperationForm.setVisible(true);
//                    this.setVisible(false);
                    this.dispose();
                    booleanForCheckIdAndPassword= false;
                    break;
                }else if(stringForLoginUserID.equalsIgnoreCase(resultSet.getString(1))){
                    jLabelForErrorOfUserPassword.setText("Password is Invalid!");
                    booleanForCheckIdAndPassword= false;
                    intForLoginTimeLimit++;
                    break;
                }else if(stringForLoginPassword.equals(resultSet.getString(3))){
                    jLabelForErrorOfUserName.setText("UserID is Invalid!");
                    booleanForCheckIdAndPassword= false;
                    break;
                }else{
                    booleanForCheckIdAndPassword= true;
                    //break;
                }
            }
            
            if(booleanForCheckIdAndPassword){
                //OptionPane.showMessageDialog(null, "ID And Password are invalid!");
                jLabelForErrorOfUserName.setText("UserID is Invalid!");
                jLabelForErrorOfUserPassword.setText("Password is Invalid!");
                intForLoginTimeLimit++;
            }
            if(intForLoginTimeLimit== 3){
                //LocalTime localTime= LocalTime.now();
                JOptionPane.showMessageDialog(this, "Try again after 30 Seconds");
                
                jLabelForCountDown.setText("Try again after : 30");
                second= 30;
                minute= 0;
                countDownTimer();
                timer.start();
                jTextFieldForLoginUserID.setEditable(false);
                jPasswordFieldForLoginPassword.setEditable(false);
                jButtonForLoginLogin.setEnabled(false);
                jLabelForCountDown.setVisible(true);
                
                
//                JOptionPane.showMessageDialog(this, "Try again after 30 Seconds");
                intForLoginTimeLimit= 0;
            }
            connection.close();
            
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Error Found");
        }
        }
            
    }//GEN-LAST:event_jButtonForLoginLoginActionPerformed

    private void jButtonForLoginCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForLoginCancelActionPerformed
        // TODO add your handling code here:
        
        
        //System.exit(0);
//        this.setVisible(false);
        this.dispose();
        
        
    }//GEN-LAST:event_jButtonForLoginCancelActionPerformed

    private void jTextFieldForLoginUserIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldForLoginUserIDKeyReleased
        // TODO add your handling code here:
        jLabelForErrorOfUserName.setText("");
    }//GEN-LAST:event_jTextFieldForLoginUserIDKeyReleased

    private void jPasswordFieldForLoginPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldForLoginPasswordKeyReleased
        // TODO add your handling code here:
        jLabelForErrorOfUserPassword.setText("");
    }//GEN-LAST:event_jPasswordFieldForLoginPasswordKeyReleased

    private void jToggleButtonForShowAndHidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonForShowAndHidePasswordMouseClicked
        // TODO add your handling code here:
        if(jToggleButtonForShowAndHidePassword.isSelected()){
            jPasswordFieldForLoginPassword.setEchoChar((char)0);
            jToggleButtonForShowAndHidePassword.setText("Hide");
        }else{
            jPasswordFieldForLoginPassword.setEchoChar('\u25cf');
//            jPasswordFieldForLoginPassword.setEchoChar('*');//It is used to change jpassword field pattern.
            jToggleButtonForShowAndHidePassword.setText("Show");
        }
    }//GEN-LAST:event_jToggleButtonForShowAndHidePasswordMouseClicked

    private void jCheckBoxForShowAndHidePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxForShowAndHidePasswordActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxForShowAndHidePassword.isSelected()){
            jPasswordFieldForLoginPassword.setEchoChar((char)0);
        }else{
            jPasswordFieldForLoginPassword.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_jCheckBoxForShowAndHidePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFormForCotching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFormForCotching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFormForCotching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFormForCotching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFormForCotching().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonForLoginCancel;
    private javax.swing.JButton jButtonForLoginLogin;
    private javax.swing.JCheckBox jCheckBoxForShowAndHidePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelForCountDown;
    private javax.swing.JLabel jLabelForErrorOfUserName;
    private javax.swing.JLabel jLabelForErrorOfUserPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldForLoginPassword;
    private javax.swing.JTextField jTextFieldForLoginUserID;
    private javax.swing.JToggleButton jToggleButtonForShowAndHidePassword;
    // End of variables declaration//GEN-END:variables
}
