/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Software;

import java.sql.*;
/**
 *
 * @author RitikCoder
 */
public class SearchedInformation extends javax.swing.JFrame{

    /**
     * Creates new form SearchedInformation
     */
    public SearchedInformation() {
        initComponents();
        setDataStudentDataMySQLToForm("RitikCoder101");
    }
    public SearchedInformation(String str){
        initComponents();
        setDataStudentDataMySQLToForm(str);
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            java.sql.Connection connection= (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/learningcomputer","root","RitikCoder@mysql");
//            String stringForQueryExecute= "Select Admin_ID from loginadmin";
//            PreparedStatement preparedStatement= connection.prepareStatement(stringForQueryExecute);
//            ResultSet resultSet= preparedStatement.executeQuery();
//            while(resultSet.next()){
//                if(str.equalsIgnoreCase(resultSet.getString(1))){
//                    System.out.println("String matched of admin table");
//                    break;
//                }
//            }
//            
//        } catch (ClassNotFoundException | SQLException ex) {
//            System.out.println("Erro Occure inside of Constructure");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    void setDataStudentDataMySQLToForm(String string){
        String stringForStudentID= string;
        jLabelForNameInformation.setText(stringForStudentID+ " - Information");
        //MySQL Connection is here.
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection connection= (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/learningcomputer","root","RitikCoder@mysql");
            String stringForExecuteQuery= "Select Student_ID, Name, DOB, Gender, Father_Name, Mother_Name, Phone_No, "
                    + "Email_ID, Admission_Date, Course, Course_Fee, Paid_Fee, Unpaid_Fee from studentdata";
            PreparedStatement preparedStatement= connection.prepareStatement(stringForExecuteQuery);
            ResultSet resultSet= preparedStatement.executeQuery();
            while(resultSet.next()){
                if(stringForStudentID.equalsIgnoreCase(resultSet.getString(1))){
                    //System.out.println("1234");
                    //System.out.println(resultSet.getString(1));
                    jTextFieldForName.setText(resultSet.getString(2));
                    jTextFieldForStudentID.setText(resultSet.getString(1));
                    jTextFieldForDOB.setText(resultSet.getString(3));
                    jTextFieldForGender.setText(resultSet.getString(4));
                    jTextFieldForCourse.setText(resultSet.getString(10));
                    jTextFieldForFatherName.setText(resultSet.getString(5));
                    jTextFieldFormotherName.setText(resultSet.getString(6));
                    jTextFieldForPhoneNo.setText(resultSet.getString(7));
                    jTextFieldForEmailID.setText(resultSet.getString(8));
                    jTextFieldForAdmissionDate.setText(resultSet.getString(9));
                    jTextFieldForCourseFee.setText(resultSet.getString(11));
                    jLabelForPaidFee.setText("Paid Fee :- "+resultSet.getString(12));
                    jLabelForUnpaidFee.setText("Unpaid Fee :- "+resultSet.getString(13));
               }
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error Occure.");
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelForNameInformation = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldForAdmissionDate = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldForDOB = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldForFatherName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldFormotherName = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldForPhoneNo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabelForUnpaidFee = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelForPaidFee = new javax.swing.JLabel();
        jTextFieldForStudentID = new javax.swing.JTextField();
        jTextFieldForGender = new javax.swing.JTextField();
        jTextFieldForCourse = new javax.swing.JTextField();
        jTextFieldForName = new javax.swing.JTextField();
        jTextFieldForEmailID = new javax.swing.JTextField();
        jTextFieldForCourseFee = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search information window");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelForNameInformation.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabelForNameInformation.setForeground(new java.awt.Color(255, 255, 255));
        jLabelForNameInformation.setText("<Name> Information");
        jPanel2.add(jLabelForNameInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("@RitikCoder.com");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 660, -1, -1));

        jTextFieldForAdmissionDate.setEditable(false);
        jTextFieldForAdmissionDate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldForAdmissionDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 250, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 255, 204));
        jLabel17.setText("Student ID :-");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 255, 204));
        jLabel18.setText("DOB :- ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 255, 204));
        jLabel19.setText("Name :- ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 255, 204));
        jLabel20.setText("Gender ;-");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jTextFieldForDOB.setEditable(false);
        jTextFieldForDOB.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldForDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 250, 30));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 255, 204));
        jLabel21.setText("Course ;-");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 255, 204));
        jLabel22.setText("Father's name ;-");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jTextFieldForFatherName.setEditable(false);
        jTextFieldForFatherName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldForFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 250, 30));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 255, 204));
        jLabel23.setText("Mother's name ;-");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jTextFieldFormotherName.setEditable(false);
        jTextFieldFormotherName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldFormotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 250, 30));

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 255, 204));
        jLabel24.setText("Phone no. :-");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jTextFieldForPhoneNo.setEditable(false);
        jTextFieldForPhoneNo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldForPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 250, 30));

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 255, 204));
        jLabel25.setText("Email ID :- ");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabelForUnpaidFee.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelForUnpaidFee.setForeground(new java.awt.Color(204, 255, 204));
        jLabelForUnpaidFee.setText("Unpaid Fee :- 00000");
        jPanel2.add(jLabelForUnpaidFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, -1, -1));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, 130, 40));

        jButton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 700, 130, 40));

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 255, 204));
        jLabel27.setText("Admission data :- ");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 255, 204));
        jLabel28.setText("Course Fee :-");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        jLabelForPaidFee.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelForPaidFee.setForeground(new java.awt.Color(204, 255, 204));
        jLabelForPaidFee.setText("Paid Fee :- 00000");
        jPanel2.add(jLabelForPaidFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        jTextFieldForStudentID.setEditable(false);
        jTextFieldForStudentID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldForStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 250, 30));

        jTextFieldForGender.setEditable(false);
        jTextFieldForGender.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldForGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 250, 30));

        jTextFieldForCourse.setEditable(false);
        jTextFieldForCourse.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldForCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 250, -1));

        jTextFieldForName.setEditable(false);
        jTextFieldForName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldForName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 250, 30));

        jTextFieldForEmailID.setEditable(false);
        jTextFieldForEmailID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldForEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 250, 30));

        jTextFieldForCourseFee.setEditable(false);
        jTextFieldForCourseFee.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldForCourseFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Software/BGForInformation.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 770));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchedInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchedInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchedInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchedInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchedInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabelForNameInformation;
    private javax.swing.JLabel jLabelForPaidFee;
    private javax.swing.JLabel jLabelForUnpaidFee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldForAdmissionDate;
    private javax.swing.JTextField jTextFieldForCourse;
    private javax.swing.JTextField jTextFieldForCourseFee;
    private javax.swing.JTextField jTextFieldForDOB;
    private javax.swing.JTextField jTextFieldForEmailID;
    private javax.swing.JTextField jTextFieldForFatherName;
    private javax.swing.JTextField jTextFieldForGender;
    private javax.swing.JTextField jTextFieldForName;
    private javax.swing.JTextField jTextFieldForPhoneNo;
    private javax.swing.JTextField jTextFieldForStudentID;
    private javax.swing.JTextField jTextFieldFormotherName;
    // End of variables declaration//GEN-END:variables
}
