/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Software;

import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.DriverManager;


/**
 *
 * @author RitikCoder
 */
public class SearchingForm extends javax.swing.JFrame {

    /**
     * Creates new form SearchingForm
     */
    //Connection connection;
    public SearchingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldForSearchRecord = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelCheckIDEmpty = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search window");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Record");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Enter ID Here");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jTextFieldForSearchRecord.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldForSearchRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForSearchRecordActionPerformed(evt);
            }
        });
        jTextFieldForSearchRecord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldForSearchRecordKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldForSearchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 330, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 51));
        jLabel3.setText("@RitikCoder.com");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 120, 40));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, 40));

        jLabelCheckIDEmpty.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabelCheckIDEmpty.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jLabelCheckIDEmpty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 310, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Software/Asus Walpaper.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldForSearchRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForSearchRecordActionPerformed
        // TODO add your handling code here:
//        String stringForSearchRecord= jTextFieldForSearchRecord.getText();
//        System.out.println(stringForSearchRecord);
    }//GEN-LAST:event_jTextFieldForSearchRecordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String stringForSearchRecord= jTextFieldForSearchRecord.getText();
        //String stringForComformPasswrodToSearchRecord= JOptionPane.showInputDialog("Enter your password here.");
        boolean booleanForCheckID= false;
        boolean booleanForCheckAdminPassword= false;
        String stringForJumpbetweenWindows= "";
//        System.out.println(stringForComformPasswrodToSearchRecord);
     
        if(jTextFieldForSearchRecord.getText().trim().isEmpty()){
            jLabelCheckIDEmpty.setText("Field of ID is Empty");
        }else{
            String stringForComformPasswrodToSearchRecord= JOptionPane.showInputDialog("Enter your password here.");
            //MySQL Database Connection.
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection connection= (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/learningcomputer", "root", "RitikCoder@mysql");
            Statement statement= connection.createStatement();
            //System.out.println("Connection Estabilizes Successfully.");
            String stringForExecuteQuery= "Select Password, Admin_ID from loginadmin";
            ResultSet resultSet= statement.executeQuery(stringForExecuteQuery);
            while(resultSet.next()){
                if(stringForComformPasswrodToSearchRecord.equals(resultSet.getString(1))){
                    booleanForCheckAdminPassword= false;
                    stringForJumpbetweenWindows= resultSet.getString(2);
                    String stringForExecuteQuery1= "Select Student_ID from studentdata";
                    resultSet= statement.executeQuery(stringForExecuteQuery1);
                    while(resultSet.next()){
                        if(stringForSearchRecord.equalsIgnoreCase(resultSet.getString(1))){
                            booleanForCheckID= false;
                            //stringForJumpbetweenWindows= stringForSearchRecord;
                            SearchedInformation searchedInformation= new SearchedInformation(stringForSearchRecord);
                            searchedInformation.setVisible(true);
                            break;
                        }else if(stringForSearchRecord.equalsIgnoreCase(stringForJumpbetweenWindows)){
                            booleanForCheckID= false;
                            TableForAllStudentData tableForAllStudentData= new TableForAllStudentData(stringForSearchRecord);
                            tableForAllStudentData.setVisible(true);
                            break;
                        }else{
                            booleanForCheckID= true;
                            //break;
                        }
                    }
                    break;
                }
                else{
                    booleanForCheckAdminPassword= true;
                    //break;
                }
            }
            if(booleanForCheckID){
                JOptionPane.showMessageDialog(null, "This Record is not found");
            }
            if(booleanForCheckAdminPassword){
                JOptionPane.showMessageDialog(null, "Password is invalid!");
            }
            
            connection.close();
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error Occure Here.");
        }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        this.setVisible(false);
        this.dispose();
//        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldForSearchRecordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldForSearchRecordKeyReleased
        // TODO add your handling code here:
        jLabelCheckIDEmpty.setText("");
    }//GEN-LAST:event_jTextFieldForSearchRecordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCheckIDEmpty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldForSearchRecord;
    // End of variables declaration//GEN-END:variables
}
