/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Software;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author codew
 */
public class UpdateFormToGetID extends javax.swing.JFrame {

    /**
     * Creates new form UpdateFormToGetID
     */
    public UpdateFormToGetID() {
        initComponents();
    }

    //Globally Variables and Reference variables;
    java.sql.Connection connection = null;
    Statement statement = null;
    PreparedStatement preparedStatement = null;
    ResultSet resultSet = null;

    //This method is used to Estabilized mysql database connection.
    public void mysqlConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String stringForURL = "jdbc:mysql://localhost:3306/learningcomputer";
            String stringForUser = "root";
            String stringForPassword = "RitikCoder@mysql";
            connection = (java.sql.Connection) DriverManager.getConnection(stringForURL, stringForUser, stringForPassword);
            statement = connection.createStatement();
            //System.out.println("Connection Estabilized successfully.");

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error Occure inside of Mysql connection method.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldForStudentID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelForInvalidId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Record");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 260, 34));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Enter Student ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 80, 145, 29));

        jTextFieldForStudentID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldForStudentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldForStudentIDKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldForStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 115, 332, 42));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 51));
        jLabel3.setText("@RitikCoder.com");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 175, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 227, 120, 35));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 227, 120, 36));

        jLabelForInvalidId.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabelForInvalidId.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jLabelForInvalidId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 250, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Software/UpdateForm1.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String stringForStudentID = jTextFieldForStudentID.getText();
        boolean booleanForCheckID = false;
        boolean booleanForCheckAdminPassword = false;
        
        //System.out.println(stringForStudentID);
        if (jTextFieldForStudentID.getText().trim().isEmpty()) {
            jLabelForInvalidId.setText("Student ID is Empty");
        } else {
            mysqlConnection();
            try {
                String stringForComformPasswrodToUpdateRecord = JOptionPane.showInputDialog("Enter your password here.");
                String stringForExecuteQuery = "Select Password from loginadmin";
                preparedStatement = connection.prepareStatement(stringForExecuteQuery);
                resultSet = preparedStatement.executeQuery();
                while (resultSet.next()) {
                    if (stringForComformPasswrodToUpdateRecord.equals(resultSet.getString(1))) {
                        booleanForCheckAdminPassword = false;
                        String stringForExecuteQuery1 = "select student_Id from studentdata";
                        preparedStatement = connection.prepareStatement(stringForExecuteQuery1);
                        resultSet = preparedStatement.executeQuery();
                        while (resultSet.next()) {
                            if (stringForStudentID.equalsIgnoreCase(resultSet.getString(1))) {
                                booleanForCheckID = false;
                                UpdateForm updateForm = new UpdateForm(stringForStudentID);
                                updateForm.setVisible(true);
                                break;
                            } else {
                                booleanForCheckID = true;
                                //break;
                            }
                        }
                        break;
                    } else {
                        booleanForCheckAdminPassword = true;
                        //break;
                    }
                }
                if (booleanForCheckID) {
                    JOptionPane.showMessageDialog(null, "This Record is not found.");
                }
                if (booleanForCheckAdminPassword) {
                    JOptionPane.showMessageDialog(null, "Password is Invalid!");
                }

                connection.close();

            } catch (SQLException exception) {
                System.out.println("Error occure inside of Update form 1");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldForStudentIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldForStudentIDKeyReleased
        // TODO add your handling code here:
        jLabelForInvalidId.setText("");
    }//GEN-LAST:event_jTextFieldForStudentIDKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateFormToGetID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateFormToGetID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateFormToGetID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateFormToGetID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateFormToGetID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelForInvalidId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldForStudentID;
    // End of variables declaration//GEN-END:variables
}
